import Navbar from "@/component/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/component/footer";
import { SessionProvider } from 'next-auth/react';
import "./globals.css";
import Provider from "./Provide";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>

        <Navbar />
        {children}
        <Footer />

        </Provider>
        </body>
    </html>
  );
}
